# A first workflow to play around with the editor
name: My First Workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user 
        run: echo "Hello world"
        shell: bash 
      - run: echo "Hello world from ${{ github.actor }}"
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - run: tree
